os:
  - linux
  - osx

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8


language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "iojs"
  - "stable"
  - "unstable"


install:
  - export CXX=g++-4.8
  - $CXX --version
  - npm install 

before_install:
  - npm install -g npm@latest
  - npm install -g node-gyp
  - rm -rf ~/.node-gyp/
